
version: "3.7"

networks:
  green-api-bots:
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1500

services:

  simple-reg-bot:
    hostname: simple-reg-bot
    restart: unless-stopped
    image: ripreal/simple-reg-bot:latest
    volumes:
       - ./credentials:/usr/src/app/credentials
    networks:
      - "green-api-bots"